#!/bin/bash

protected_branch='master'  
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]  
then  
    read -p "You're about to push master, you are ignorining the team policy, the whole team will blame you if there are destructive changes. Please create a pull request in GubHub and you should be fine.
 Do you fill lucky and want to continue? [y|n].  " -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
	echo -e "\n Git Flow spirit forbids the push! Please create the pull request.\n"
    fi
    exit 1 # push will not execute
else  
    exit 0 # push will execute
fi  
